### PR TITLE
Feature/Extend kanji set to include iteration character in isKanji check

### PR DESCRIPTION
**Pull request by crushingCodes**
Currently, the check for kanji does not include the char for representing a kanji repetition, e.g. in 人々 the 々 is ignored. Added a test and an extra check for this character since it is counted as a kanji.

A reference to the character here:
[Reference](https://jisho.org/word/%E3%80%85)

By the way I am very grateful for all the work in this package and making it public, it helps a lot!

### CODE REVIEW

**Comment by crushingCodes** [comment]
Unfortunately, this was not the silver bullet to my original issue. I was hoping tokenized would count 人々 as one kanji word, but I think it's counting it as pronunciation, so still working on the final fix.

**Comment by DJTB** [comment]
I think you're probably right with the suggestion to remove `々` from `isCharJapanesePunctuation` given that its splitting `々` from its associated character in tokenize.

I slept on this issue and it seems someone else ran into it recently and patched it downstream here https://github.com/DJTB/react-furi/pull/6/files 

Your suggestion however should fix both issues, since they stem from the same cause, and the react-furi fix could be reverted.

**Comment by crushingCodes** [comment]
@DJTB not really sure how to get this approved, I opened this 2 years ago and you are the first to comment lol. I think its because i was also doing some custom stuff with furigana that i must have run into a similar problem with your react furi lib

**Comment by DJTB** [comment]
It'll probably be up to me to implement and test it (since this PR was a first pass, not actually your second suggestion). Just wanted to leave a comment with my thoughts.

**Pull request closed without merging**
