### PR TITLE
[Breaking] Feature: include '々' iteration character in kanji, exclude from JA punctuation

### PR DESCRIPTION
**Pull request by DJTB**
Closes #113

Currently, Wanakana considers `々` to be punctuation (due to where it lies in unicode ranges, alongside other pure punctuation symbols), though in practice it functions like a kanji character. This causes minor issues such as `tokenize()` splitting up words like `人々` incorrectly and `isKanji()` reporting false for `人々`.

This PR now considers `々` to be a kanji character, and excludes it from punctuation checks.
Please see modified tests to see which functions are affected and #113 for prior discussion, as well as https://github.com/DJTB/react-furi/pull/6.

This doesn't really affect the core usage of Wanakana (as an IME) but peripheral utils that we provide. Whenever 々 comes up currently it is behaving incorrectly, so despite considering this a `fix` I don't want consumers updating if they see a patch bump (`5.1.1`). Since it changes existing behaviour perhaps it should be a major release?

@mimshwright @scottnicolson @vietqhoang do you have any concerns merging this?
Do you prefer a major `6.0.0` or minor `5.2.0` with breaking changes listed in release/changelog?

### CODE REVIEW

**Comment by DJTB** [comment]
Also fixes #156 and closes #157

**Comment by DJTB** [comment]
Also merged tokenize docs update since this modifies them as well.
Fixes #156 and closes #157

**Comment by vietqhoang** [comment]
Did a first pass review. Nothing really stood out to me as far as the changes go. My first thoughts is I do agree the repeater should be considered more of a kanji than a punctuation.

As for the preference on how to increment the version, to me this is more of a minor version than a major version. The changes don't really add anything significant nor does it break the API.

**Comment by DJTB** [comment]
> As for the preference on how to increment the version, to me this is more of a minor version than a major version. The changes don't really add anything significant nor does it break the API.

You're right that a major bump doesn't make much sense, I was being overly cautious since it changes some behaviour 😅(albeit for the better).

**Review by vietqhoang — APPROVED** [review]

**Pull request merged**
