### PR TITLE
Typescript definitions

### PR DESCRIPTION
**Pull request by TabithaLarkin**
This PR implements Typescript compilation as discussed in #141. However, I have taken the approach to incrementally enhance the UX for this, rather than do a wholesale refactor of the project, or move to a different build system as discussed in the comments.

A number of packages did have to be updated in order to enable this, but there is no change to any actual code. More information about what packages have been updated and why can be found on the first commit message. The tsconfig option `allowJs` has been used to generate types from the javascript files, rather than convereting all files, and associated code to Typescript. This allows for package consumers to use the type definitions from the package, published through the `types` property that was added into the `release.js` script.

This all results in the following defintion file being generated

```ts
declare function bind(element?: HTMLInputElement | HTMLTextAreaElement, options?: DefaultOptions, debug?: boolean): void;
declare function unbind(element: HTMLInputElement | HTMLTextAreaElement, debug?: boolean): void;
declare function isRomaji(input?: string, allowed?: RegExp): boolean;
declare function isJapanese(input?: string, allowed?: RegExp): boolean;
declare function isKana(input?: string): boolean;
declare function isHiragana(input?: string): boolean;
declare function isKatakana(input?: string): boolean;
declare function isMixed(input?: string, options?: {
    passKanji: boolean;
}): boolean;
declare function isKanji(input?: string): boolean;
declare function toRomaji(input?: string, options?: DefaultOptions, map?: {
    [index: string]: string;
}): string;
declare function toKana(input?: string, options?: DefaultOptions, map?: {
    [index: string]: string;
}): string;
declare function toHiragana(input?: string, options?: DefaultOptions): string;
declare function toKatakana(input?: string, options?: DefaultOptions): string;
declare function stripOkurigana(input?: string, { leading, matchKanji }?: {
    leading?: boolean;
    matchKanji?: string;
}): string;
declare function tokenize(input: string, { compact, detailed }?: {
    compact?: boolean;
    detailed?: boolean;
}): string[] | {
    type: string;
    value: string;
}[];
declare const VERSION = "5.2.0";
declare const TO_KANA_METHODS: {
    HIRAGANA: "toHiragana";
    KATAKANA: "toKatakana";
};
declare const ROMANIZATIONS: {
    HEPBURN: "hepburn";
};
type DefaultOptions = {
    useObsoleteKana?: boolean;
    passRomaji?: boolean;
    convertLongVowelMark?: boolean;
    upcaseKatakana?: boolean;
    IMEMode?: boolean | "toHiragana" | "toKatakana";
    romanization?: "hepburn";
    customKanaMapping?: {
        [index: string]: string;
    };
    customRomajiMapping?: {
        [index: string]: string;
    };
};
export { bind, unbind, isRomaji, isJapanese, isKana, isHiragana, isKatakana, isMixed, isKanji, toRomaji, toKana, toHiragana, toKatakana, stripOkurigana, tokenize, VERSION, TO_KANA_METHODS, ROMANIZATIONS };
//# sourceMappingURL=index.d.ts.map
```

I'm not sure how you would like to proceed with testing this, and would be open to any guidance or experience anyone has in this area.

### CODE REVIEW

**Comment by DJTB** [comment]
This is a great addition, thanks for contributing!
It's probably easiest to test this manually by creating a release locally and importing to another project.
I'll give this a go over the next week or so, and check the docs site compiles correctly as well.

**Comment by TabithaLarkin** [comment]
Just a heads up, I've now tested this locally, by adjusting the package.json to point at the types file and dropping the types file into the correct folder in a local install. It seems to work as expected!

image

**Comment by DJTB** [comment]
Sorry for the delay, I've taken a quick look and the docs site no longer compiles due to invalid syntax.
E.g. https://github.com/WaniKani/WanaKana/commit/3df06abf57426787711c7970b13b9488ba7ca285#diff-cc3afe3f35bff79cef9a329c0b73c22fbcd68698520d712457c1a271332e3bf9R14

You can try running `npm run docs` to build and `npm run docs:view` to view locally.

Would you mind taking a look at this?

**Comment by TabithaLarkin** [comment]
Sure thing. I'll take a look at it this weekend.

**Comment by TabithaLarkin** [comment]
Hey sorry for the delay. Things have been pretty hectic on my end.

I've updated the doc generation to handle typescript files, and changed any conflicting types. Generated typescript types are not affected by this change. I've also changed some casing of typings back, such as `string` to `String` in order to match the previous documentation. It should be good to go now!

**Comment by DJTB** [comment]
> Hey sorry for the delay. Things have been pretty hectic on my end.
> 
> I've updated the doc generation to handle typescript files, and changed any conflicting types. Generated typescript types are not affected by this change. I've also changed some casing of typings back, such as `string` to `String` in order to match the previous documentation. It should be good to go now!

No problem, busy here as well, but I'll do my best to take another look at it this week.

**Review by DJTB — APPROVED** [review]
I made some minor changes, but otherwise this is looking good now 👍 
I'll publish on the weekend for you.

**Pull request merged**
